[project]
name = "keycloak-collection"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ansible-core>=2.19.3",
]

[dependency-groups]
dev = [
    "ansible-lint>=25.9.2",
]
