keycloak_pod_name: kc
keycloak_pod_file: "~/.config/containers/systemd/{{ keycloak_pod_name }}.pod"
keycloak_postgres_container_file: "~/.config/containers/systemd/{{ keycloak_pod_name }}-postgres.container"
keycloak_postgres_volume_file: "~/.config/containers/systemd/pgdata.volume"
keycloak_postgres_secrets_file: "~/.postgres.env"
keycloak_postgres_password: UNSET
keycloak_keycloak_data_volume_file: "~/.config/containers/systemd/keycloak_data.volume"
keycloak_keycloak_container_file: "~/.config/containers/systemd/{{ keycloak_pod_name }}-keycloak.container"
keycloak_keycloak_secrets_file: "~/.keycloak.env"
keycloak_bootstrap_mode: false
keycloak_bootstrap_admin:
  username: admin
  password: UNSET
keycloak_publish_port: 127.0.0.1:8080
keycloak_hostname: UNSET
